# .github/workflows/codegen-agents.yml
name: Codegen Agents

on:
  workflow_call:
    inputs:
      prompt:
        description: "Optional prompt to pass to Codegen"
        required: false
        type: string
        default: ""
      spec_path:
        description: "Explicit spec path"
        required: false
        type: string
        default: ""
      specs_glob:
        description: "Glob override for discovering specs"
        required: false
        type: string
        default: ""
      wait:
        description: "Wait for remote task completion"
        required: false
        type: boolean
        default: true
      python_version:
        description: "Python version for SDK"
        required: false
        type: string
        default: "3.12"
      target_repo:
        description: "Expected GitHub repository slug"
        required: false
        type: string
        default: ""
    secrets:
      CODEGEN_ORG_ID:
        required: true
      CODEGEN_TOKEN:
        required: true
      CODEGEN_REPO_ID:
        required: false

permissions:
  contents: read

concurrency:
  group: codegen-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    name: Run Codegen Agent
    runs-on: ubuntu-latest
    env:
      PYTHONWARNINGS: ignore
    steps:
      - name: Guard forked pull requests
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
        run: |
          echo "::error::Codegen workflows do not run on pull requests from forks."
          exit 1

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}

      - name: Install Codegen SDK
        run: |
          set -euo pipefail
          python -m pip install --disable-pip-version-check --upgrade codegen

      - name: Preflight validation
        id: preflight
        env:
          CODEGEN_ORG_ID: ${{ secrets.CODEGEN_ORG_ID }}
          CODEGEN_TOKEN: ${{ secrets.CODEGEN_TOKEN }}
          TARGET_REPO_INPUT: ${{ inputs.target_repo }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          set -euo pipefail
          if [ -z "${CODEGEN_ORG_ID:-}" ]; then
            echo "::error::Missing CODEGEN_ORG_ID secret."
            exit 1
          fi
          if [ -z "${CODEGEN_TOKEN:-}" ]; then
            echo "::error::Missing CODEGEN_TOKEN secret."
            exit 1
          fi

          origin_url=$(git config --get remote.origin.url || true)
          if [ -z "${origin_url}" ]; then
            echo "::error::Unable to determine git remote origin URL."
            exit 1
          fi

          target_repo="${TARGET_REPO_INPUT:-$GITHUB_REPOSITORY}"
          repo_slug="${origin_url}"
          case "${repo_slug}" in
            git@github.com:*)
              repo_slug="${repo_slug#git@github.com:}"
              ;;
            ssh://git@github.com/*)
              repo_slug="${repo_slug#ssh://git@github.com/}"
              ;;
            https://github.com/*)
              repo_slug="${repo_slug#https://github.com/}"
              ;;
            http://github.com/*)
              repo_slug="${repo_slug#http://github.com/}"
              ;;
            git://github.com/*)
              repo_slug="${repo_slug#git://github.com/}"
              ;;
          esac
          repo_slug="${repo_slug%.git}"
          repo_slug="${repo_slug#/}"
          if [ -z "${repo_slug}" ]; then
            echo "::error::Unable to parse repository slug from git remote URL."
            exit 1
          fi
          if [ "${repo_slug}" != "${target_repo}" ]; then
            echo "::error::Git remote slug '${repo_slug}' does not match expected '${target_repo}'."
            exit 1
          fi
          {
            echo "target-repo=${target_repo}"
            echo "repo-slug=${repo_slug}"
          } >>"${GITHUB_OUTPUT}"

      - name: Resolve Codegen repository id
        id: repo_id
        env:
          CODEGEN_REPO_ID_SECRET: ${{ secrets.CODEGEN_REPO_ID }}
        run: |
          set -euo pipefail
          if [ -n "${CODEGEN_REPO_ID_SECRET:-}" ]; then
            {
              printf 'repo-id=%s\n' "${CODEGEN_REPO_ID_SECRET}"
            } >>"${GITHUB_OUTPUT}"
            echo "::notice::Using Codegen repository id from secret."
            exit 0
          fi
          if [ ! -f .codegen/repo-id ]; then
            echo "::error::Codegen repository id not provided. Add CODEGEN_REPO_ID secret or commit .codegen/repo-id."
            exit 1
          fi
          repo_id=$(head -n 1 .codegen/repo-id | tr -d '\r\n\t ')
          if [ -z "${repo_id}" ]; then
            echo "::error::File .codegen/repo-id is empty."
            exit 1
          fi
          {
            printf 'repo-id=%s\n' "${repo_id}"
          } >>"${GITHUB_OUTPUT}"
          echo "::notice::Using Codegen repository id from .codegen/repo-id."

      - name: Prepare prompt
        id: prompt
        env:
          INPUT_PROMPT: ${{ inputs.prompt }}
          INPUT_SPEC_PATH: ${{ inputs.spec_path }}
          INPUT_SPECS_GLOB: ${{ inputs.specs_glob }}
          LEGACY_DISCOVERY: 1
        run: |
          set -euo pipefail
          python .github/scripts/codegen_workflow.py prepare-prompt

      - name: Run Codegen task
        id: run_agent
        env:
          CODEGEN_ORG_ID: ${{ secrets.CODEGEN_ORG_ID }}
          CODEGEN_TOKEN: ${{ secrets.CODEGEN_TOKEN }}
          RESOLVED_REPO_ID: ${{ steps.repo_id.outputs.repo-id }}
          PROMPT: ${{ steps.prompt.outputs.prompt }}
        run: |
          set -euo pipefail
          export CODEGEN_REPO_ID="${RESOLVED_REPO_ID}"
          export REPOSITORY_ID="${RESOLVED_REPO_ID}"
          python .github/scripts/codegen_workflow.py run-task

      - name: Wait for task completion
        id: wait
        if: ${{ inputs.wait && steps.run_agent.outputs.task_id }}
        env:
          CODEGEN_ORG_ID: ${{ secrets.CODEGEN_ORG_ID }}
          CODEGEN_TOKEN: ${{ secrets.CODEGEN_TOKEN }}
          RESOLVED_REPO_ID: ${{ steps.repo_id.outputs.repo-id }}
          TASK_ID: ${{ steps.run_agent.outputs.task_id }}
        run: |
          set -euo pipefail
          export CODEGEN_REPO_ID="${RESOLVED_REPO_ID}"
          export REPOSITORY_ID="${RESOLVED_REPO_ID}"
          python .github/scripts/codegen_workflow.py wait-task

      - name: Validate generated pull request
        env:
          TARGET_REPO: ${{ steps.preflight.outputs.target-repo }}
          PR_URL_WAIT: ${{ steps.wait.outputs.pr_url }}
          PR_URL_INITIAL: ${{ steps.run_agent.outputs.pr_url }}
        run: |
          set -euo pipefail
          pr_url="${PR_URL_WAIT}"
          if [ -z "${pr_url}" ]; then
            pr_url="${PR_URL_INITIAL}"
          fi
          if [ -z "${pr_url}" ]; then
            echo "::notice::No pull request URL provided by Codegen."
            exit 0
          fi
          python .github/scripts/codegen_workflow.py validate-pr

      - name: Summary
        env:
          PR_URL_WAIT: ${{ steps.wait.outputs.pr_url }}
          PR_URL_INITIAL: ${{ steps.run_agent.outputs.pr_url }}
        run: |
          set -euo pipefail
          python .github/scripts/codegen_workflow.py summary
