# .github/workflows/codegen-on-push.yml
name: Codegen on Spec Push

on:
  push:
    paths:
      - .agent-os/specs/**
      - .specify/specs/**
  workflow_dispatch:
    inputs:
      prompt:
        description: "Override prompt"
        required: false
        default: ""
      spec_path:
        description: "Override spec path"
        required: false
        default: ""
      wait:
        description: "Wait for Codegen completion"
        required: false
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  run:
    name: Run Codegen on push
    uses: ./.github/workflows/codegen-agents.yml
    with:
      require_agentos: true
      wait: ${{ github.event_name == 'workflow_dispatch' && inputs.wait || true }}
      prompt: ${{ github.event_name == 'workflow_dispatch' && inputs.prompt || '' }}
      spec_path: ${{ github.event_name == 'workflow_dispatch' && inputs.spec_path || '' }}
      target_repo: ${{ github.repository }}
    secrets:
      CODEGEN_ORG_ID: ${{ secrets.CODEGEN_ORG_ID }}
      CODEGEN_TOKEN: ${{ secrets.CODEGEN_TOKEN }}
      CODEGEN_REPO_ID: ${{ secrets.CODEGEN_REPO_ID }}
