# .github/workflows/seed-agentos.yml
name: Seed Agent OS

on:
  workflow_dispatch:
    inputs:
      wait:
        description: "Wait for Codegen completion"
        required: false
        default: true
        type: boolean

permissions:
  contents: read

jobs:
  seed:
    name: Bootstrap Agent OS
    uses: ./.github/workflows/codegen-agents.yml
    with:
      require_agentos: false
      wait: ${{ inputs.wait }}
      target_repo: ${{ github.repository }}
      prompt: |
        You are responsible for bootstrapping Agent OS in ${{ github.repository }}.
        - Verify that `git remote get-url origin` resolves to https://github.com/${{ github.repository }} and abort if it does not.
        - Install the base toolchain:
          curl -fsSL https://raw.githubusercontent.com/agent-os/agent-os/v1.4.1/setup/base.sh | bash -s -- --cursor
        - When `.agent-os/` is missing, run `~/.agent-os/setup/project.sh --no-base --cursor`.
        - Determine the Codegen repository ID if available (for example from the API response) and write it to `.codegen/repo-id`.
        - Create a new branch `chore/agentos-bootstrap`, add only the relevant files, and commit with a clear message when there are staged changes.
        - Push the branch and open a pull request summarizing the bootstrap work.
    secrets:
      CODEGEN_ORG_ID: ${{ secrets.CODEGEN_ORG_ID }}
      CODEGEN_TOKEN: ${{ secrets.CODEGEN_TOKEN }}
      CODEGEN_REPO_ID: ${{ secrets.CODEGEN_REPO_ID }}
